; Song New song in Lightweight format (V1).
; Generated by Arkos Tracker 2.

gameover_song_Start
gameover_song_StartDisarkGenerateExternalLabel

gameover_song_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
gameover_song_DisarkByteRegionEnd0
gameover_song_DisarkPointerRegionStart1
	dw gameover_song_FmInstrumentTable
	dw gameover_song_ArpeggioTable
	dw gameover_song_PitchTable
; Table of the Subsongs.
	dw gameover_song_Subsong0
gameover_song_DisarkPointerRegionEnd1

; The Arpeggio table.
gameover_song_ArpeggioTable
gameover_song_DisarkWordRegionStart2
	dw 0
gameover_song_DisarkWordRegionEnd2
gameover_song_DisarkPointerRegionStart3
gameover_song_DisarkPointerRegionEnd3

; The Pitch table.
gameover_song_PitchTable
gameover_song_DisarkWordRegionStart4
	dw 0
gameover_song_DisarkWordRegionEnd4
gameover_song_DisarkPointerRegionStart5
gameover_song_DisarkPointerRegionEnd5

; The FM Instrument table.
gameover_song_FmInstrumentTable
gameover_song_DisarkPointerRegionStart6
	dw gameover_song_FmInstrument0
	dw gameover_song_FmInstrument1
	dw gameover_song_FmInstrument2
gameover_song_DisarkPointerRegionEnd6

gameover_song_DisarkByteRegionStart7
gameover_song_FmInstrument0
	db 255	; Speed.

gameover_song_FmInstrument0Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
gameover_song_DisarkPointerRegionStart8
	dw gameover_song_FmInstrument0Loop	; Loops.
gameover_song_DisarkPointerRegionEnd8

gameover_song_FmInstrument1
	db 0	; Speed.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 4	; End the instrument.
gameover_song_DisarkPointerRegionStart9
	dw gameover_song_FmInstrument0Loop	; Loop to silence.
gameover_song_DisarkPointerRegionEnd9

gameover_song_FmInstrument2
	db 0	; Speed.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 4	; End the instrument.
gameover_song_DisarkPointerRegionStart10
	dw gameover_song_FmInstrument0Loop	; Loop to silence.
gameover_song_DisarkPointerRegionEnd10

gameover_song_DisarkByteRegionEnd7
gameover_song_Subsong0DisarkByteRegionStart0
; Song New song, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

gameover_song_Subsong0
	db 4	; Initial speed.

; The Linker.
; Pattern 0
	db 5	; State byte.
	db 63	; New height.
gameover_song_Subsong0DisarkPointerRegionStart1
	dw gameover_song_Subsong0_Track0, gameover_song_Subsong0_Track1, gameover_song_Subsong0_Track1
gameover_song_Subsong0DisarkPointerRegionEnd1
; The tracks.

; Pattern 1
	db 1	; State byte.
gameover_song_Subsong0DisarkPointerRegionStart2
	dw gameover_song_Subsong0_Track2, gameover_song_Subsong0_Track1, gameover_song_Subsong0_Track1
gameover_song_Subsong0DisarkPointerRegionEnd2
; The tracks.

; Pattern 2
gameover_song_Subsong0loop
	db 1	; State byte.
gameover_song_Subsong0DisarkPointerRegionStart3
	dw gameover_song_Subsong0_Track1, gameover_song_Subsong0_Track1, gameover_song_Subsong0_Track1
gameover_song_Subsong0DisarkPointerRegionEnd3
; The tracks.

	db 0	; End of the subsong.
gameover_song_Subsong0DisarkPointerRegionStart4
	dw gameover_song_Subsong0loop
gameover_song_Subsong0DisarkPointerRegionEnd4

; The Tracks.
gameover_song_Subsong0_Track0
	db 191, 16	; Escaped note: 16.
	db 2	; New instrument: 1.
	db 161	; Note: 57.
	db 4	; New instrument: 2.
	db 191, 16	; Escaped note: 16.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 63, 16	; Escaped note: 16.
	db 62	; Short wait: 1.

	db 63, 16	; Escaped note: 16.
	db 62	; Short wait: 1.

	db 63, 19	; Escaped note: 19.
	db 62	; Short wait: 1.

	db 156	; Note: 52.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 19	; Escaped note: 19.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 154	; Note: 50.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 21	; Escaped note: 21.
	db 2	; New instrument: 1.
	db 154	; Note: 50.
	db 4	; New instrument: 2.
	db 191, 19	; Escaped note: 19.
	db 2	; New instrument: 1.
	db 156	; Note: 52.
	db 4	; New instrument: 2.
	db 191, 21	; Escaped note: 21.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 159	; Note: 55.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 19	; Escaped note: 19.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 154	; Note: 50.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 191, 21	; Escaped note: 21.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 63, 21	; Escaped note: 21.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 21	; Escaped note: 21.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 63, 19	; Escaped note: 19.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 16	; Escaped note: 16.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 14	; Escaped note: 14.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 161	; Note: 57.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 191, 14	; Escaped note: 14.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 159	; Note: 55.
	db 4	; New instrument: 2.
	db 61, 4	; Long wait: 5.


gameover_song_Subsong0_Track1
	db 61, 63	; Long wait: 64.


gameover_song_Subsong0_Track2
	db 191, 21	; Escaped note: 21.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 63, 19	; Escaped note: 19.
	db 62	; Short wait: 1.

	db 63, 21	; Escaped note: 21.
	db 62	; Short wait: 1.

	db 63, 19	; Escaped note: 19.
	db 62	; Short wait: 1.

	db 63, 21	; Escaped note: 21.
	db 62	; Short wait: 1.

	db 63, 19	; Escaped note: 19.
	db 62	; Short wait: 1.

	db 63, 21	; Escaped note: 21.
	db 62	; Short wait: 1.

	db 63, 19	; Escaped note: 19.
	db 62	; Short wait: 1.

	db 63, 21	; Escaped note: 21.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 31	; Note: 55.
	db 62	; Short wait: 1.

	db 191, 16	; Escaped note: 16.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 154	; Note: 50.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 31	; Note: 55.
	db 62	; Short wait: 1.

	db 191, 14	; Escaped note: 14.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 63, 14	; Escaped note: 14.
	db 62	; Short wait: 1.

	db 63, 14	; Escaped note: 14.
	db 62	; Short wait: 1.

	db 63, 19	; Escaped note: 19.
	db 61, 4	; Long wait: 5.

	db 63, 21	; Escaped note: 21.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 61, 8	; Long wait: 9.


gameover_song_Subsong0DisarkByteRegionEnd0
