; Song New song in Lightweight format (V1).
; Generated by Arkos Tracker 2.

intro_screen_Start
intro_screen_StartDisarkGenerateExternalLabel

intro_screen_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
intro_screen_DisarkByteRegionEnd0
intro_screen_DisarkPointerRegionStart1
	dw intro_screen_FmInstrumentTable
	dw intro_screen_ArpeggioTable
	dw intro_screen_PitchTable
; Table of the Subsongs.
	dw intro_screen_Subsong0
intro_screen_DisarkPointerRegionEnd1

; The Arpeggio table.
intro_screen_ArpeggioTable
intro_screen_DisarkWordRegionStart2
	dw 0
intro_screen_DisarkWordRegionEnd2
intro_screen_DisarkPointerRegionStart3
intro_screen_DisarkPointerRegionEnd3

; The Pitch table.
intro_screen_PitchTable
intro_screen_DisarkWordRegionStart4
	dw 0
intro_screen_DisarkWordRegionEnd4
intro_screen_DisarkPointerRegionStart5
intro_screen_DisarkPointerRegionEnd5

; The FM Instrument table.
intro_screen_FmInstrumentTable
intro_screen_DisarkPointerRegionStart6
	dw intro_screen_FmInstrument0
	dw intro_screen_FmInstrument1
	dw intro_screen_FmInstrument2
	dw intro_screen_FmInstrument3
intro_screen_DisarkPointerRegionEnd6

intro_screen_DisarkByteRegionStart7
intro_screen_FmInstrument0
	db 255	; Speed.

intro_screen_FmInstrument0Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
intro_screen_DisarkPointerRegionStart8
	dw intro_screen_FmInstrument0Loop	; Loops.
intro_screen_DisarkPointerRegionEnd8

intro_screen_FmInstrument1
	db 0	; Speed.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 4	; End the instrument.
intro_screen_DisarkPointerRegionStart9
	dw intro_screen_FmInstrument0Loop	; Loop to silence.
intro_screen_DisarkPointerRegionEnd9

intro_screen_FmInstrument2
	db 0	; Speed.

	db 189	; Volume: 15.
	db 24	; Arpeggio: 12.

	db 189	; Volume: 15.
	db 26	; Arpeggio: 13.

	db 189	; Volume: 15.
	db 32	; Arpeggio: 16.

	db 189	; Volume: 15.
	db 18	; Arpeggio: 9.

	db 61	; Volume: 15.

	db 189	; Volume: 15.
	db 18	; Arpeggio: 9.

	db 189	; Volume: 15.
	db 28	; Arpeggio: 14.

	db 4	; End the instrument.
intro_screen_DisarkPointerRegionStart10
	dw intro_screen_FmInstrument0Loop	; Loop to silence.
intro_screen_DisarkPointerRegionEnd10

intro_screen_FmInstrument3
	db 0	; Speed.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 4	; End the instrument.
intro_screen_DisarkPointerRegionStart11
	dw intro_screen_FmInstrument0Loop	; Loop to silence.
intro_screen_DisarkPointerRegionEnd11

intro_screen_DisarkByteRegionEnd7
intro_screen_Subsong0DisarkByteRegionStart0
; Song New song, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

intro_screen_Subsong0
	db 4	; Initial speed.

; The Linker.
; Pattern 0
intro_screen_Subsong0loop
	db 5	; State byte.
	db 63	; New height.
intro_screen_Subsong0DisarkPointerRegionStart1
	dw intro_screen_Subsong0_Track0, intro_screen_Subsong0_Track1, intro_screen_Subsong0_Track1
intro_screen_Subsong0DisarkPointerRegionEnd1
; The tracks.

; Pattern 1
	db 1	; State byte.
intro_screen_Subsong0DisarkPointerRegionStart2
	dw intro_screen_Subsong0_Track2, intro_screen_Subsong0_Track1, intro_screen_Subsong0_Track1
intro_screen_Subsong0DisarkPointerRegionEnd2
; The tracks.

; Pattern 2
	db 1	; State byte.
intro_screen_Subsong0DisarkPointerRegionStart3
	dw intro_screen_Subsong0_Track0, intro_screen_Subsong0_Track1, intro_screen_Subsong0_Track1
intro_screen_Subsong0DisarkPointerRegionEnd3
; The tracks.

; Pattern 3
	db 1	; State byte.
intro_screen_Subsong0DisarkPointerRegionStart4
	dw intro_screen_Subsong0_Track3, intro_screen_Subsong0_Track1, intro_screen_Subsong0_Track1
intro_screen_Subsong0DisarkPointerRegionEnd4
; The tracks.

; Pattern 4
	db 1	; State byte.
intro_screen_Subsong0DisarkPointerRegionStart5
	dw intro_screen_Subsong0_Track0, intro_screen_Subsong0_Track1, intro_screen_Subsong0_Track1
intro_screen_Subsong0DisarkPointerRegionEnd5
; The tracks.

	db 0	; End of the subsong.
intro_screen_Subsong0DisarkPointerRegionStart6
	dw intro_screen_Subsong0loop
intro_screen_Subsong0DisarkPointerRegionEnd6

; The Tracks.
intro_screen_Subsong0_Track0
	db 191, 21	; Escaped note: 21.
	db 2	; New instrument: 1.
	db 173	; Note: 69.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 43	; Note: 67.
	db 191, 21	; Escaped note: 21.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 191, 21	; Escaped note: 21.
	db 2	; New instrument: 1.
	db 61, 4	; Long wait: 5.

	db 63, 21	; Escaped note: 21.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 2	; Note: 26.
	db 190	; Short wait: 3.

	db 63, 21	; Escaped note: 21.
	db 61, 6	; Long wait: 7.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 191, 19	; Escaped note: 19.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


intro_screen_Subsong0_Track1
	db 61, 63	; Long wait: 64.


intro_screen_Subsong0_Track2
	db 191, 21	; Escaped note: 21.
	db 2	; New instrument: 1.
	db 61, 4	; Long wait: 5.

	db 63, 21	; Escaped note: 21.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 190	; Short wait: 3.

	db 9	; Note: 33.
	db 61, 6	; Long wait: 7.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 191, 21	; Escaped note: 21.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 2	; Note: 26.
	db 61, 4	; Long wait: 5.

	db 2	; Note: 26.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 2	; Note: 26.
	db 190	; Short wait: 3.

	db 4	; Note: 28.
	db 190	; Short wait: 3.

	db 0	; Note: 24.
	db 62	; Short wait: 1.

	db 63, 19	; Escaped note: 19.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


intro_screen_Subsong0_Track3
	db 191, 21	; Escaped note: 21.
	db 2	; New instrument: 1.
	db 61, 4	; Long wait: 5.

	db 63, 21	; Escaped note: 21.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 190	; Short wait: 3.

	db 9	; Note: 33.
	db 61, 6	; Long wait: 7.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 2	; Note: 26.
	db 61, 4	; Long wait: 5.

	db 2	; Note: 26.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 2	; Note: 26.
	db 190	; Short wait: 3.

	db 0	; Note: 24.
	db 190	; Short wait: 3.

	db 0	; Note: 24.
	db 62	; Short wait: 1.

	db 63, 19	; Escaped note: 19.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 191, 16	; Escaped note: 16.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


intro_screen_Subsong0DisarkByteRegionEnd0
