; Song New song in Lightweight format (V1).
; Generated by Arkos Tracker 2.

music_Start
music_StartDisarkGenerateExternalLabel

music_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
music_DisarkByteRegionEnd0
music_DisarkPointerRegionStart1
	dw music_FmInstrumentTable
	dw music_ArpeggioTable
	dw music_PitchTable
; Table of the Subsongs.
	dw music_Subsong0
music_DisarkPointerRegionEnd1

; The Arpeggio table.
music_ArpeggioTable
music_DisarkWordRegionStart2
	dw 0
music_DisarkWordRegionEnd2
music_DisarkPointerRegionStart3
music_DisarkPointerRegionEnd3

; The Pitch table.
music_PitchTable
music_DisarkWordRegionStart4
	dw 0
music_DisarkWordRegionEnd4
music_DisarkPointerRegionStart5
music_DisarkPointerRegionEnd5

; The FM Instrument table.
music_FmInstrumentTable
music_DisarkPointerRegionStart6
	dw music_FmInstrument0
	dw music_FmInstrument1
	dw music_FmInstrument2
	dw music_FmInstrument3
	dw music_FmInstrument4
music_DisarkPointerRegionEnd6

music_DisarkByteRegionStart7
music_FmInstrument0
	db 255	; Speed.

music_FmInstrument0Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
music_DisarkPointerRegionStart8
	dw music_FmInstrument0Loop	; Loops.
music_DisarkPointerRegionEnd8

music_FmInstrument1
	db 0	; Speed.

	db 61	; Volume: 15.

	db 125	; Volume: 15.
	dw -4	; Pitch: -4.

	db 125	; Volume: 15.
	dw -2	; Pitch: -2.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 4	; End the instrument.
music_DisarkPointerRegionStart9
	dw music_FmInstrument0Loop	; Loop to silence.
music_DisarkPointerRegionEnd9

music_FmInstrument2
	db 0	; Speed.

	db 189	; Volume: 15.
	db 24	; Arpeggio: 12.

	db 189	; Volume: 15.
	db 26	; Arpeggio: 13.

	db 189	; Volume: 15.
	db 32	; Arpeggio: 16.

	db 189	; Volume: 15.
	db 18	; Arpeggio: 9.

	db 189	; Volume: 15.
	db 14	; Arpeggio: 7.

	db 4	; End the instrument.
music_DisarkPointerRegionStart10
	dw music_FmInstrument0Loop	; Loop to silence.
music_DisarkPointerRegionEnd10

music_FmInstrument3
	db 0	; Speed.

	db 189	; Volume: 15.
	db 6	; Arpeggio: 3.

	db 189	; Volume: 15.
	db 14	; Arpeggio: 7.

	db 4	; End the instrument.
music_DisarkPointerRegionStart11
	dw music_FmInstrument0Loop	; Loop to silence.
music_DisarkPointerRegionEnd11

music_FmInstrument4
	db 0	; Speed.

music_FmInstrument4Loop	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 0	; Volume: 0.

	db 4	; End the instrument.
music_DisarkPointerRegionStart12
	dw music_FmInstrument4Loop	; Loops.
music_DisarkPointerRegionEnd12

music_DisarkByteRegionEnd7
music_Subsong0DisarkByteRegionStart0
; Song New song, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

music_Subsong0
	db 3	; Initial speed.

; The Linker.
; Pattern 0
music_Subsong0loop
	db 5	; State byte.
	db 63	; New height.
music_Subsong0DisarkPointerRegionStart1
	dw music_Subsong0_Track0, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd1
; The tracks.

; Pattern 1
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart2
	dw music_Subsong0_Track2, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd2
; The tracks.

; Pattern 2
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart3
	dw music_Subsong0_Track0, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd3
; The tracks.

; Pattern 3
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart4
	dw music_Subsong0_Track3, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd4
; The tracks.

; Pattern 4
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart5
	dw music_Subsong0_Track4, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd5
; The tracks.

; Pattern 5
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart6
	dw music_Subsong0_Track5, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd6
; The tracks.

; Pattern 6
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart7
	dw music_Subsong0_Track4, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd7
; The tracks.

; Pattern 7
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart8
	dw music_Subsong0_Track6, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd8
; The tracks.

; Pattern 8
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart9
	dw music_Subsong0_Track7, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd9
; The tracks.

; Pattern 9
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart10
	dw music_Subsong0_Track8, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd10
; The tracks.

; Pattern 10
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart11
	dw music_Subsong0_Track7, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd11
; The tracks.

; Pattern 11
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart12
	dw music_Subsong0_Track9, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd12
; The tracks.

; Pattern 12
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart13
	dw music_Subsong0_Track4, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd13
; The tracks.

; Pattern 13
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart14
	dw music_Subsong0_Track5, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd14
; The tracks.

; Pattern 14
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart15
	dw music_Subsong0_Track4, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd15
; The tracks.

; Pattern 15
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart16
	dw music_Subsong0_Track6, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd16
; The tracks.

; Pattern 16
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart17
	dw music_Subsong0_Track10, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd17
; The tracks.

; Pattern 17
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart18
	dw music_Subsong0_Track11, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd18
; The tracks.

; Pattern 18
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart19
	dw music_Subsong0_Track10, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd19
; The tracks.

; Pattern 19
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart20
	dw music_Subsong0_Track12, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd20
; The tracks.

; Pattern 20
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart21
	dw music_Subsong0_Track4, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd21
; The tracks.

; Pattern 21
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart22
	dw music_Subsong0_Track5, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd22
; The tracks.

; Pattern 22
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart23
	dw music_Subsong0_Track4, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd23
; The tracks.

; Pattern 23
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart24
	dw music_Subsong0_Track6, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd24
; The tracks.

; Pattern 24
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart25
	dw music_Subsong0_Track13, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd25
; The tracks.

; Pattern 25
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart26
	dw music_Subsong0_Track14, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd26
; The tracks.

; Pattern 26
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart27
	dw music_Subsong0_Track13, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd27
; The tracks.

; Pattern 27
	db 1	; State byte.
music_Subsong0DisarkPointerRegionStart28
	dw music_Subsong0_Track15, music_Subsong0_Track1, music_Subsong0_Track1
music_Subsong0DisarkPointerRegionEnd28
; The tracks.

	db 0	; End of the subsong.
music_Subsong0DisarkPointerRegionStart29
	dw music_Subsong0loop
music_Subsong0DisarkPointerRegionEnd29

; The Tracks.
music_Subsong0_Track0
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 61, 4	; Long wait: 5.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


music_Subsong0_Track1
	db 61, 63	; Long wait: 64.


music_Subsong0_Track2
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 61, 4	; Long wait: 5.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


music_Subsong0_Track3
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 142	; Note: 38.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 61, 4	; Long wait: 5.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


music_Subsong0_Track4
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 45	; Note: 69.
	db 47	; Note: 71.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 45	; Note: 69.
	db 62	; Short wait: 1.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


music_Subsong0_Track5
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 45	; Note: 69.
	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 38	; Note: 62.
	db 40	; Note: 64.
	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


music_Subsong0_Track6
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 63, 74	; Escaped note: 74.
	db 63, 76	; Escaped note: 76.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 79	; Escaped note: 79.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 191, 76	; Escaped note: 76.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 191, 76	; Escaped note: 76.
	db 8	; New instrument: 4.
	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 191, 74	; Escaped note: 74.
	db 8	; New instrument: 4.
	db 142	; Note: 38.
	db 2	; New instrument: 1.
	db 191, 74	; Escaped note: 74.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 63, 72	; Escaped note: 72.
	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 83	; Escaped note: 83.
	db 8	; New instrument: 4.
	db 63, 76	; Escaped note: 76.
	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 191, 81	; Escaped note: 81.
	db 8	; New instrument: 4.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 191, 83	; Escaped note: 83.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


music_Subsong0_Track7
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 156	; Note: 52.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 156	; Note: 52.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 154	; Note: 50.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 154	; Note: 50.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 161	; Note: 57.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 161	; Note: 57.
	db 8	; New instrument: 4.
	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 161	; Note: 57.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 126	; Short wait: 2.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 154	; Note: 50.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


music_Subsong0_Track8
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 156	; Note: 52.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 156	; Note: 52.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 166	; Note: 62.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 166	; Note: 62.
	db 8	; New instrument: 4.
	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 161	; Note: 57.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 156	; Note: 52.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 154	; Note: 50.
	db 8	; New instrument: 4.
	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 126	; Short wait: 2.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 161	; Note: 57.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 161	; Note: 57.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


music_Subsong0_Track9
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 166	; Note: 62.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 161	; Note: 57.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 161	; Note: 57.
	db 8	; New instrument: 4.
	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 161	; Note: 57.
	db 8	; New instrument: 4.
	db 142	; Note: 38.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 166	; Note: 62.
	db 8	; New instrument: 4.
	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 126	; Short wait: 2.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 74	; Escaped note: 74.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 191, 76	; Escaped note: 76.
	db 8	; New instrument: 4.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 175	; Note: 71.
	db 8	; New instrument: 4.

music_Subsong0_Track10
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 191, 76	; Escaped note: 76.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 191, 74	; Escaped note: 74.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 191, 79	; Escaped note: 79.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 81	; Escaped note: 81.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 191, 76	; Escaped note: 76.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 191, 74	; Escaped note: 74.
	db 8	; New instrument: 4.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 191, 76	; Escaped note: 76.
	db 8	; New instrument: 4.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


music_Subsong0_Track11
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 191, 79	; Escaped note: 79.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 191, 81	; Escaped note: 81.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 191, 76	; Escaped note: 76.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 166	; Note: 62.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


music_Subsong0_Track12
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 191, 74	; Escaped note: 74.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 76	; Escaped note: 76.
	db 8	; New instrument: 4.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 191, 79	; Escaped note: 79.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 142	; Note: 38.
	db 2	; New instrument: 1.
	db 191, 81	; Escaped note: 81.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 191, 83	; Escaped note: 83.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 191, 83	; Escaped note: 83.
	db 8	; New instrument: 4.
	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 191, 83	; Escaped note: 83.
	db 8	; New instrument: 4.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 76	; Escaped note: 76.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 191, 79	; Escaped note: 79.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 191, 81	; Escaped note: 81.
	db 8	; New instrument: 4.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 191, 76	; Escaped note: 76.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


music_Subsong0_Track13
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 43	; Note: 67.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 166	; Note: 62.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


music_Subsong0_Track14
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 45	; Note: 69.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


music_Subsong0_Track15
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 175	; Note: 71.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 191, 74	; Escaped note: 74.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 168	; Note: 64.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 142	; Note: 38.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 161	; Note: 57.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 173	; Note: 69.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


music_Subsong0DisarkByteRegionEnd0
