; Song New song in Lightweight format (V1).
; Generated by Arkos Tracker 2.

success_song_Start
success_song_StartDisarkGenerateExternalLabel

success_song_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
success_song_DisarkByteRegionEnd0
success_song_DisarkPointerRegionStart1
	dw success_song_FmInstrumentTable
	dw success_song_ArpeggioTable
	dw success_song_PitchTable
; Table of the Subsongs.
	dw success_song_Subsong0
success_song_DisarkPointerRegionEnd1

; The Arpeggio table.
success_song_ArpeggioTable
success_song_DisarkWordRegionStart2
	dw 0
success_song_DisarkWordRegionEnd2
success_song_DisarkPointerRegionStart3
success_song_DisarkPointerRegionEnd3

; The Pitch table.
success_song_PitchTable
success_song_DisarkWordRegionStart4
	dw 0
success_song_DisarkWordRegionEnd4
success_song_DisarkPointerRegionStart5
success_song_DisarkPointerRegionEnd5

; The FM Instrument table.
success_song_FmInstrumentTable
success_song_DisarkPointerRegionStart6
	dw success_song_FmInstrument0
	dw success_song_FmInstrument1
	dw success_song_FmInstrument2
	dw success_song_FmInstrument3
	dw success_song_FmInstrument4
success_song_DisarkPointerRegionEnd6

success_song_DisarkByteRegionStart7
success_song_FmInstrument0
	db 255	; Speed.

success_song_FmInstrument0Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
success_song_DisarkPointerRegionStart8
	dw success_song_FmInstrument0Loop	; Loops.
success_song_DisarkPointerRegionEnd8

success_song_FmInstrument1
	db 0	; Speed.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 4	; End the instrument.
success_song_DisarkPointerRegionStart9
	dw success_song_FmInstrument0Loop	; Loop to silence.
success_song_DisarkPointerRegionEnd9

success_song_FmInstrument2
	db 0	; Speed.

	db 189	; Volume: 15.
	db 24	; Arpeggio: 12.

	db 189	; Volume: 15.
	db 26	; Arpeggio: 13.

	db 189	; Volume: 15.
	db 32	; Arpeggio: 16.

	db 189	; Volume: 15.
	db 18	; Arpeggio: 9.

	db 61	; Volume: 15.

	db 189	; Volume: 15.
	db 18	; Arpeggio: 9.

	db 189	; Volume: 15.
	db 28	; Arpeggio: 14.

	db 4	; End the instrument.
success_song_DisarkPointerRegionStart10
	dw success_song_FmInstrument0Loop	; Loop to silence.
success_song_DisarkPointerRegionEnd10

success_song_FmInstrument3
	db 0	; Speed.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 4	; End the instrument.
success_song_DisarkPointerRegionStart11
	dw success_song_FmInstrument0Loop	; Loop to silence.
success_song_DisarkPointerRegionEnd11

success_song_FmInstrument4
	db 0	; Speed.

	db 125	; Volume: 15.
	dw -4	; Pitch: -4.

success_song_FmInstrument4Loop	db 61	; Volume: 15.

	db 4	; End the instrument.
success_song_DisarkPointerRegionStart12
	dw success_song_FmInstrument4Loop	; Loops.
success_song_DisarkPointerRegionEnd12

success_song_DisarkByteRegionEnd7
success_song_Subsong0DisarkByteRegionStart0
; Song New song, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

success_song_Subsong0
	db 5	; Initial speed.

; The Linker.
; Pattern 0
success_song_Subsong0loop
	db 5	; State byte.
	db 63	; New height.
success_song_Subsong0DisarkPointerRegionStart1
	dw success_song_Subsong0_Track0, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd1
; The tracks.

; Pattern 1
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart2
	dw success_song_Subsong0_Track2, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd2
; The tracks.

; Pattern 2
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart3
	dw success_song_Subsong0_Track3, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd3
; The tracks.

; Pattern 3
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart4
	dw success_song_Subsong0_Track4, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd4
; The tracks.

; Pattern 4
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart5
	dw success_song_Subsong0_Track5, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd5
; The tracks.

; Pattern 5
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart6
	dw success_song_Subsong0_Track6, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd6
; The tracks.

; Pattern 6
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart7
	dw success_song_Subsong0_Track5, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd7
; The tracks.

; Pattern 7
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart8
	dw success_song_Subsong0_Track7, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd8
; The tracks.

; Pattern 8
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart9
	dw success_song_Subsong0_Track8, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd9
; The tracks.

; Pattern 9
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart10
	dw success_song_Subsong0_Track9, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd10
; The tracks.

; Pattern 10
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart11
	dw success_song_Subsong0_Track10, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd11
; The tracks.

; Pattern 11
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart12
	dw success_song_Subsong0_Track11, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd12
; The tracks.

; Pattern 12
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart13
	dw success_song_Subsong0_Track12, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd13
; The tracks.

; Pattern 13
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart14
	dw success_song_Subsong0_Track13, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd14
; The tracks.

; Pattern 14
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart15
	dw success_song_Subsong0_Track12, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd15
; The tracks.

; Pattern 15
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart16
	dw success_song_Subsong0_Track14, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd16
; The tracks.

; Pattern 16
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart17
	dw success_song_Subsong0_Track8, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd17
; The tracks.

; Pattern 17
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart18
	dw success_song_Subsong0_Track9, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd18
; The tracks.

; Pattern 18
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart19
	dw success_song_Subsong0_Track10, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd19
; The tracks.

; Pattern 19
	db 1	; State byte.
success_song_Subsong0DisarkPointerRegionStart20
	dw success_song_Subsong0_Track15, success_song_Subsong0_Track1, success_song_Subsong0_Track1
success_song_Subsong0DisarkPointerRegionEnd20
; The tracks.

	db 0	; End of the subsong.
success_song_Subsong0DisarkPointerRegionStart21
	dw success_song_Subsong0loop
success_song_Subsong0DisarkPointerRegionEnd21

; The Tracks.
success_song_Subsong0_Track0
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 11	; Note: 35.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 190	; Short wait: 3.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 190	; Short wait: 3.

	db 6	; Note: 30.
	db 190	; Short wait: 3.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 190	; Short wait: 3.

	db 11	; Note: 35.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 190	; Short wait: 3.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 190	; Short wait: 3.

	db 6	; Note: 30.
	db 190	; Short wait: 3.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 15	; Note: 39.
	db 62	; Short wait: 1.

	db 13	; Note: 37.
	db 62	; Short wait: 1.


success_song_Subsong0_Track1
	db 61, 63	; Long wait: 64.


success_song_Subsong0_Track2
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 11	; Note: 35.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 190	; Short wait: 3.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 190	; Short wait: 3.

	db 6	; Note: 30.
	db 190	; Short wait: 3.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 190	; Short wait: 3.

	db 11	; Note: 35.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 190	; Short wait: 3.

	db 11	; Note: 35.
	db 190	; Short wait: 3.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.


success_song_Subsong0_Track3
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 7	; Note: 31.
	db 141	; Note: 37.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


success_song_Subsong0_Track4
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.


success_song_Subsong0_Track5
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 37	; Note: 61.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 42	; Note: 66.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 165	; Note: 61.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 7	; Note: 31.
	db 141	; Note: 37.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


success_song_Subsong0_Track6
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 42	; Note: 66.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 151	; Note: 47.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


success_song_Subsong0_Track7
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 42	; Note: 66.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 165	; Note: 61.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 39	; Note: 63.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 165	; Note: 61.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


success_song_Subsong0_Track8
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 30	; Note: 54.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 153	; Note: 49.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 165	; Note: 61.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 153	; Note: 49.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 7	; Note: 31.
	db 141	; Note: 37.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


success_song_Subsong0_Track9
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 30	; Note: 54.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 153	; Note: 49.
	db 8	; New instrument: 4.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 167	; Note: 63.
	db 8	; New instrument: 4.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 165	; Note: 61.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.


success_song_Subsong0_Track10
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 175	; Note: 71.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 42	; Note: 66.
	db 47	; Note: 71.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 30	; Note: 54.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 153	; Note: 49.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 175	; Note: 71.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 39	; Note: 63.
	db 165	; Note: 61.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 191, 78	; Escaped note: 78.
	db 6	; New instrument: 3.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 191, 73	; Escaped note: 73.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 153	; Note: 49.
	db 8	; New instrument: 4.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 141	; Note: 37.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


success_song_Subsong0_Track11
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 175	; Note: 71.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 63, 73	; Escaped note: 73.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 191, 78	; Escaped note: 78.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 191, 78	; Escaped note: 78.
	db 6	; New instrument: 3.
	db 63, 75	; Escaped note: 75.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 191, 73	; Escaped note: 73.
	db 6	; New instrument: 3.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 30	; Note: 54.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 153	; Note: 49.
	db 8	; New instrument: 4.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 175	; Note: 71.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 167	; Note: 63.
	db 8	; New instrument: 4.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 44	; Note: 68.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 165	; Note: 61.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 165	; Note: 61.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.


success_song_Subsong0_Track12
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 42	; Note: 66.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 39	; Note: 63.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 165	; Note: 61.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 35	; Note: 59.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 47	; Note: 71.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 37	; Note: 61.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 47	; Note: 71.
	db 63, 75	; Escaped note: 75.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 175	; Note: 71.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 7	; Note: 31.
	db 141	; Note: 37.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


success_song_Subsong0_Track13
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 47	; Note: 71.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 37	; Note: 61.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 37	; Note: 61.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 165	; Note: 61.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 165	; Note: 61.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 165	; Note: 61.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 191, 73	; Escaped note: 73.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 47	; Note: 71.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 37	; Note: 61.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 175	; Note: 71.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 175	; Note: 71.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 175	; Note: 71.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


success_song_Subsong0_Track14
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 78	; Escaped note: 78.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 191, 78	; Escaped note: 78.
	db 6	; New instrument: 3.
	db 63, 73	; Escaped note: 73.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 4	; Note: 28.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 63, 73	; Escaped note: 73.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 191, 73	; Escaped note: 73.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 73	; Escaped note: 73.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 191, 73	; Escaped note: 73.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 47	; Note: 71.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 35	; Note: 59.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 165	; Note: 61.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 165	; Note: 61.
	db 6	; New instrument: 3.

success_song_Subsong0_Track15
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 175	; Note: 71.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 63, 73	; Escaped note: 73.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 191, 78	; Escaped note: 78.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 8	; New instrument: 4.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 191, 78	; Escaped note: 78.
	db 6	; New instrument: 3.
	db 63, 75	; Escaped note: 75.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 191, 73	; Escaped note: 73.
	db 6	; New instrument: 3.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 30	; Note: 54.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 153	; Note: 49.
	db 8	; New instrument: 4.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 175	; Note: 71.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 167	; Note: 63.
	db 8	; New instrument: 4.
	db 139	; Note: 35.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 170	; Note: 66.
	db 6	; New instrument: 3.
	db 44	; Note: 68.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 6	; Note: 30.
	db 165	; Note: 61.
	db 6	; New instrument: 3.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 158	; Note: 54.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 165	; Note: 61.
	db 8	; New instrument: 4.
	db 134	; Note: 30.
	db 2	; New instrument: 1.
	db 163	; Note: 59.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 27	; Note: 51.
	db 30	; Note: 54.
	db 35	; Note: 59.

success_song_Subsong0DisarkByteRegionEnd0
